version: "3.3"
services:
  travelapp-db:
    container_name: travelapp-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "travelapp_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-travelapp-db:/var/lib/mysql
volumes:
  vol-travelapp-db:
